hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
hibernate.connection.url=jdbc:mysql://localhost:3306/movie?useSSL=false&serverTimezone=UTC
hibernate.connection.username=nikita
hibernate.connection.password=nikita

hibernate.hbm2ddl.auto=validate

hibernate.show_sql=true
hibernate.format_sql=true
hibernate.highlight_sql=true

hibernate.enable_lazy_load_no_trans=false

hibernate.jdbc.batch_size=20

hibernate.jdbc.time_zone=UTC